// Try & Catch :-)

/* The try statement allows you to define a block of code to be tested for errors while it is being executed. 

The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
*/

console.log("Hello");
console.log("Hello");

try{
    console.log(a);
} catch(error){
    console.log("Caught an error... a is not defined");
    console.log(error);
}

console.log("Hiii");
console.log("Hiii");